version: "3.9"
services:
  db:
    image: postgres:15
    container_name: library_database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: library_service
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgressql://admin:password@db:5432/library
    volumes:
      - .:/app

volumes:
  postgres_data:
